export const C = {
  CREATE_NEW_SESSION: 'CREATE_NEW_SESSION',
  ABORT_SESSION: 'ABORT_SESSION',
  SET_WEIGHT: 'SET_WEIGHT',
  SET_NEXT_WEIGHT: 'SET_NEXT_WEIGHT',
  SET_POSITION: 'SET_POSITION',
  NEXT_EXERCISE: 'NEXT_EXERCISE',
  PREVIOUS_EXERCISE: 'PREVIOUS_EXERCISE',
  WORKOUT_COMPLETE: 'WORKOUT_COMPLETE',
  UNDO_WORKOUT_COMPLETE: 'UNDO_WORKOUT_COMPLETE',
  STORE_WORKOUT: 'STORE_WORKOUT',
}

export const positions = {
  SET_WORKOUT_WEIGHT: 'SET_WORKOUT_WEIGHT',
  SHOW_SETS: 'SHOW_SETS',
  SET_NEXT_WEIGHT: 'SET_NEXT_WEIGHT',
}
